ERROR - 2025-05-21 14:32:12 --> Error connecting to the database: mysqli_sql_exception: Access denied for user ''@'localhost' (using password: YES) in D:\wamp64\www\pmtvs\system\Database\MySQLi\Connection.php:201
Stack trace:
#0 D:\wamp64\www\pmtvs\system\Database\MySQLi\Connection.php(201): mysqli->real_connect('localhost', '', Object(SensitiveParameterValue), '', 3306, '', 0)
#1 D:\wamp64\www\pmtvs\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 D:\wamp64\www\pmtvs\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
#3 D:\wamp64\www\pmtvs\system\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 D:\wamp64\www\pmtvs\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#5 D:\wamp64\www\pmtvs\system\BaseModel.php(843): CodeIgniter\Model->doInsert(Array)
#6 D:\wamp64\www\pmtvs\system\Model.php(800): CodeIgniter\BaseModel->insert(Array, true)
#7 D:\wamp64\www\pmtvs\app\Controllers\Api.php(40): CodeIgniter\Model->insert(Array)
#8 D:\wamp64\www\pmtvs\system\CodeIgniter.php(933): App\Controllers\Api->createMember()
#9 D:\wamp64\www\pmtvs\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Api))
#10 D:\wamp64\www\pmtvs\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 D:\wamp64\www\pmtvs\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#12 D:\wamp64\www\pmtvs\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 D:\wamp64\www\pmtvs\public\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user ''@'localhost' (using password: YES) in D:\wamp64\www\pmtvs\system\Database\MySQLi\Connection.php:246
Stack trace:
#0 D:\wamp64\www\pmtvs\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 D:\wamp64\www\pmtvs\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
#2 D:\wamp64\www\pmtvs\system\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#3 D:\wamp64\www\pmtvs\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#4 D:\wamp64\www\pmtvs\system\BaseModel.php(843): CodeIgniter\Model->doInsert(Array)
#5 D:\wamp64\www\pmtvs\system\Model.php(800): CodeIgniter\BaseModel->insert(Array, true)
#6 D:\wamp64\www\pmtvs\app\Controllers\Api.php(40): CodeIgniter\Model->insert(Array)
#7 D:\wamp64\www\pmtvs\system\CodeIgniter.php(933): App\Controllers\Api->createMember()
#8 D:\wamp64\www\pmtvs\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Api))
#9 D:\wamp64\www\pmtvs\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 D:\wamp64\www\pmtvs\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#11 D:\wamp64\www\pmtvs\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#12 D:\wamp64\www\pmtvs\public\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#13 {main}
CRITICAL - 2025-05-21 14:32:12 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: YES)
[Method: POST, Route: api/create-member]
in SYSTEMPATH\Database\BaseConnection.php on line 467.
 1 SYSTEMPATH\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `users` (`name`, `position`, `address`, `image`) VALUES (:name:, :position:, :address:, :image:)', [...], false)
 3 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 4 SYSTEMPATH\BaseModel.php(843): CodeIgniter\Model->doInsert([...])
 5 SYSTEMPATH\Model.php(800): CodeIgniter\BaseModel->insert([...], true)
 6 APPPATH\Controllers\Api.php(40): CodeIgniter\Model->insert([...])
 7 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Api->createMember()
 8 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Api))
 9 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
12 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2025-05-21 14:35:49 --> Error connecting to the database: mysqli_sql_exception: Access denied for user ''@'localhost' (using password: YES) in D:\wamp64\www\pmtvs\system\Database\MySQLi\Connection.php:201
Stack trace:
#0 D:\wamp64\www\pmtvs\system\Database\MySQLi\Connection.php(201): mysqli->real_connect('localhost', '', Object(SensitiveParameterValue), '', 3306, '', 0)
#1 D:\wamp64\www\pmtvs\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 D:\wamp64\www\pmtvs\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
#3 D:\wamp64\www\pmtvs\system\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 D:\wamp64\www\pmtvs\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#5 D:\wamp64\www\pmtvs\system\BaseModel.php(843): CodeIgniter\Model->doInsert(Array)
#6 D:\wamp64\www\pmtvs\system\Model.php(800): CodeIgniter\BaseModel->insert(Array, true)
#7 D:\wamp64\www\pmtvs\app\Controllers\Api.php(40): CodeIgniter\Model->insert(Array)
#8 D:\wamp64\www\pmtvs\system\CodeIgniter.php(933): App\Controllers\Api->createMember()
#9 D:\wamp64\www\pmtvs\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Api))
#10 D:\wamp64\www\pmtvs\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 D:\wamp64\www\pmtvs\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#12 D:\wamp64\www\pmtvs\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 D:\wamp64\www\pmtvs\public\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user ''@'localhost' (using password: YES) in D:\wamp64\www\pmtvs\system\Database\MySQLi\Connection.php:246
Stack trace:
#0 D:\wamp64\www\pmtvs\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 D:\wamp64\www\pmtvs\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
#2 D:\wamp64\www\pmtvs\system\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#3 D:\wamp64\www\pmtvs\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#4 D:\wamp64\www\pmtvs\system\BaseModel.php(843): CodeIgniter\Model->doInsert(Array)
#5 D:\wamp64\www\pmtvs\system\Model.php(800): CodeIgniter\BaseModel->insert(Array, true)
#6 D:\wamp64\www\pmtvs\app\Controllers\Api.php(40): CodeIgniter\Model->insert(Array)
#7 D:\wamp64\www\pmtvs\system\CodeIgniter.php(933): App\Controllers\Api->createMember()
#8 D:\wamp64\www\pmtvs\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Api))
#9 D:\wamp64\www\pmtvs\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 D:\wamp64\www\pmtvs\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#11 D:\wamp64\www\pmtvs\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#12 D:\wamp64\www\pmtvs\public\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#13 {main}
CRITICAL - 2025-05-21 14:35:49 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: YES)
[Method: POST, Route: api/create-member]
in SYSTEMPATH\Database\BaseConnection.php on line 467.
 1 SYSTEMPATH\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `users` (`name`, `position`, `address`, `image`) VALUES (:name:, :position:, :address:, :image:)', [...], false)
 3 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 4 SYSTEMPATH\BaseModel.php(843): CodeIgniter\Model->doInsert([...])
 5 SYSTEMPATH\Model.php(800): CodeIgniter\BaseModel->insert([...], true)
 6 APPPATH\Controllers\Api.php(40): CodeIgniter\Model->insert([...])
 7 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Api->createMember()
 8 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Api))
 9 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
12 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2025-05-21 15:18:06 --> Error connecting to the database: mysqli_sql_exception: Access denied for user ''@'localhost' (using password: YES) in D:\wamp64\www\pmtvs\system\Database\MySQLi\Connection.php:201
Stack trace:
#0 D:\wamp64\www\pmtvs\system\Database\MySQLi\Connection.php(201): mysqli->real_connect('localhost', '', Object(SensitiveParameterValue), '', 3306, '', 0)
#1 D:\wamp64\www\pmtvs\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 D:\wamp64\www\pmtvs\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
#3 D:\wamp64\www\pmtvs\system\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 D:\wamp64\www\pmtvs\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#5 D:\wamp64\www\pmtvs\system\BaseModel.php(843): CodeIgniter\Model->doInsert(Array)
#6 D:\wamp64\www\pmtvs\system\Model.php(800): CodeIgniter\BaseModel->insert(Array, true)
#7 D:\wamp64\www\pmtvs\app\Controllers\Api.php(40): CodeIgniter\Model->insert(Array)
#8 D:\wamp64\www\pmtvs\system\CodeIgniter.php(933): App\Controllers\Api->createMember()
#9 D:\wamp64\www\pmtvs\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Api))
#10 D:\wamp64\www\pmtvs\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 D:\wamp64\www\pmtvs\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#12 D:\wamp64\www\pmtvs\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 D:\wamp64\www\pmtvs\public\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user ''@'localhost' (using password: YES) in D:\wamp64\www\pmtvs\system\Database\MySQLi\Connection.php:246
Stack trace:
#0 D:\wamp64\www\pmtvs\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 D:\wamp64\www\pmtvs\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
#2 D:\wamp64\www\pmtvs\system\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#3 D:\wamp64\www\pmtvs\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#4 D:\wamp64\www\pmtvs\system\BaseModel.php(843): CodeIgniter\Model->doInsert(Array)
#5 D:\wamp64\www\pmtvs\system\Model.php(800): CodeIgniter\BaseModel->insert(Array, true)
#6 D:\wamp64\www\pmtvs\app\Controllers\Api.php(40): CodeIgniter\Model->insert(Array)
#7 D:\wamp64\www\pmtvs\system\CodeIgniter.php(933): App\Controllers\Api->createMember()
#8 D:\wamp64\www\pmtvs\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Api))
#9 D:\wamp64\www\pmtvs\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 D:\wamp64\www\pmtvs\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#11 D:\wamp64\www\pmtvs\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#12 D:\wamp64\www\pmtvs\public\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#13 {main}
CRITICAL - 2025-05-21 15:18:06 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: YES)
[Method: POST, Route: api/create-member]
in SYSTEMPATH\Database\BaseConnection.php on line 467.
 1 SYSTEMPATH\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `users` (`name`, `position`, `address`, `image`) VALUES (:name:, :position:, :address:, :image:)', [...], false)
 3 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 4 SYSTEMPATH\BaseModel.php(843): CodeIgniter\Model->doInsert([...])
 5 SYSTEMPATH\Model.php(800): CodeIgniter\BaseModel->insert([...], true)
 6 APPPATH\Controllers\Api.php(40): CodeIgniter\Model->insert([...])
 7 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Api->createMember()
 8 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Api))
 9 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
12 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2025-05-21 15:18:13 --> Error connecting to the database: mysqli_sql_exception: Access denied for user ''@'localhost' (using password: YES) in D:\wamp64\www\pmtvs\system\Database\MySQLi\Connection.php:201
Stack trace:
#0 D:\wamp64\www\pmtvs\system\Database\MySQLi\Connection.php(201): mysqli->real_connect('localhost', '', Object(SensitiveParameterValue), '', 3306, '', 0)
#1 D:\wamp64\www\pmtvs\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 D:\wamp64\www\pmtvs\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
#3 D:\wamp64\www\pmtvs\system\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 D:\wamp64\www\pmtvs\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#5 D:\wamp64\www\pmtvs\system\BaseModel.php(843): CodeIgniter\Model->doInsert(Array)
#6 D:\wamp64\www\pmtvs\system\Model.php(800): CodeIgniter\BaseModel->insert(Array, true)
#7 D:\wamp64\www\pmtvs\app\Controllers\Api.php(40): CodeIgniter\Model->insert(Array)
#8 D:\wamp64\www\pmtvs\system\CodeIgniter.php(933): App\Controllers\Api->createMember()
#9 D:\wamp64\www\pmtvs\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Api))
#10 D:\wamp64\www\pmtvs\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 D:\wamp64\www\pmtvs\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#12 D:\wamp64\www\pmtvs\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 D:\wamp64\www\pmtvs\public\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user ''@'localhost' (using password: YES) in D:\wamp64\www\pmtvs\system\Database\MySQLi\Connection.php:246
Stack trace:
#0 D:\wamp64\www\pmtvs\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 D:\wamp64\www\pmtvs\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
#2 D:\wamp64\www\pmtvs\system\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#3 D:\wamp64\www\pmtvs\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#4 D:\wamp64\www\pmtvs\system\BaseModel.php(843): CodeIgniter\Model->doInsert(Array)
#5 D:\wamp64\www\pmtvs\system\Model.php(800): CodeIgniter\BaseModel->insert(Array, true)
#6 D:\wamp64\www\pmtvs\app\Controllers\Api.php(40): CodeIgniter\Model->insert(Array)
#7 D:\wamp64\www\pmtvs\system\CodeIgniter.php(933): App\Controllers\Api->createMember()
#8 D:\wamp64\www\pmtvs\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Api))
#9 D:\wamp64\www\pmtvs\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 D:\wamp64\www\pmtvs\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#11 D:\wamp64\www\pmtvs\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#12 D:\wamp64\www\pmtvs\public\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#13 {main}
CRITICAL - 2025-05-21 15:18:13 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: YES)
[Method: POST, Route: api/create-member]
in SYSTEMPATH\Database\BaseConnection.php on line 467.
 1 SYSTEMPATH\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `users` (`name`, `position`, `address`, `image`) VALUES (:name:, :position:, :address:, :image:)', [...], false)
 3 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 4 SYSTEMPATH\BaseModel.php(843): CodeIgniter\Model->doInsert([...])
 5 SYSTEMPATH\Model.php(800): CodeIgniter\BaseModel->insert([...], true)
 6 APPPATH\Controllers\Api.php(40): CodeIgniter\Model->insert([...])
 7 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Api->createMember()
 8 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Api))
 9 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
12 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2025-05-21 17:13:59 --> mysqli_sql_exception: Table 'j2k5e6r5_pmtvs.users' doesn't exist in D:\wamp64\www\pmtvs\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 D:\wamp64\www\pmtvs\system\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `us...', 0)
#1 D:\wamp64\www\pmtvs\system\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 D:\wamp64\www\pmtvs\system\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 D:\wamp64\www\pmtvs\system\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 D:\wamp64\www\pmtvs\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#5 D:\wamp64\www\pmtvs\system\BaseModel.php(843): CodeIgniter\Model->doInsert(Array)
#6 D:\wamp64\www\pmtvs\system\Model.php(800): CodeIgniter\BaseModel->insert(Array, true)
#7 D:\wamp64\www\pmtvs\app\Controllers\Api.php(40): CodeIgniter\Model->insert(Array)
#8 D:\wamp64\www\pmtvs\system\CodeIgniter.php(933): App\Controllers\Api->createMember()
#9 D:\wamp64\www\pmtvs\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Api))
#10 D:\wamp64\www\pmtvs\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 D:\wamp64\www\pmtvs\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#12 D:\wamp64\www\pmtvs\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 D:\wamp64\www\pmtvs\public\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 {main}
CRITICAL - 2025-05-21 17:13:59 --> CodeIgniter\Database\Exceptions\DatabaseException: Table 'j2k5e6r5_pmtvs.users' doesn't exist
[Method: POST, Route: api/create-member]
in SYSTEMPATH\Database\BaseConnection.php on line 692.
 1 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `users` (`name`, `position`, `address`, `image`) VALUES (:name:, :position:, :address:, :image:)', [...], false)
 2 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(843): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(800): CodeIgniter\BaseModel->insert([...], true)
 5 APPPATH\Controllers\Api.php(40): CodeIgniter\Model->insert([...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Api->createMember()
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Api))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-05-21 17:13:59 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Table 'j2k5e6r5_pmtvs.users' doesn't exist
in SYSTEMPATH\Database\MySQLi\Connection.php on line 332.
 1 SYSTEMPATH\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `users` (`name`, `position`, `address`, `image`) VALUES (\'village development \', \'test\', \'74/A Bhawanipur Cololy, Near Annapurna Road\', \'1747847639_eaa16c365bdcbda5184f.jpg\')')
 2 SYSTEMPATH\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `users` (`name`, `position`, `address`, `image`) VALUES (\'village development \', \'test\', \'74/A Bhawanipur Cololy, Near Annapurna Road\', \'1747847639_eaa16c365bdcbda5184f.jpg\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `users` (`name`, `position`, `address`, `image`) VALUES (:name:, :position:, :address:, :image:)', [...], false)
 4 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(843): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(800): CodeIgniter\BaseModel->insert([...], true)
 7 APPPATH\Controllers\Api.php(40): CodeIgniter\Model->insert([...])
 8 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Api->createMember()
 9 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Api))
10 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
13 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-05-21 17:13:59 --> [Caused by] mysqli_sql_exception: Table 'j2k5e6r5_pmtvs.users' doesn't exist
in SYSTEMPATH\Database\MySQLi\Connection.php on line 327.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `users` (`name`, `position`, `address`, `image`) VALUES (\'village development \', \'test\', \'74/A Bhawanipur Cololy, Near Annapurna Road\', \'1747847639_eaa16c365bdcbda5184f.jpg\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `users` (`name`, `position`, `address`, `image`) VALUES (\'village development \', \'test\', \'74/A Bhawanipur Cololy, Near Annapurna Road\', \'1747847639_eaa16c365bdcbda5184f.jpg\')')
 3 SYSTEMPATH\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `users` (`name`, `position`, `address`, `image`) VALUES (\'village development \', \'test\', \'74/A Bhawanipur Cololy, Near Annapurna Road\', \'1747847639_eaa16c365bdcbda5184f.jpg\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `users` (`name`, `position`, `address`, `image`) VALUES (:name:, :position:, :address:, :image:)', [...], false)
 5 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(843): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(800): CodeIgniter\BaseModel->insert([...], true)
 8 APPPATH\Controllers\Api.php(40): CodeIgniter\Model->insert([...])
 9 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Api->createMember()
10 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Api))
11 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
